### ISSUE TITLE
show actual errors in IntelliJ

### ISSUE THREAD

**Issue by ccapndave** [durkiewicz/elm-plugin#32] opened 2016-09-22 07:17 UTC
Do I need to set something up to get actual errors displayed, or is this something that isn't possible yet?

For example, is there a way to get this red squiggly underlined?

``` elm
x : Int
x = "Hello"
```

**Comment by bgourlie** [comment] 2016-09-22 20:34
In order for it to display compile errors, it would need to invoke the compiler and parse the results as you type.  This is something that's not currently implemented AFAIK.

**Comment by durkiewicz** [comment] 2016-11-05 21:41
Duplicate of https://github.com/durkiewicz/elm-plugin/issues/27

**Closed by durkiewicz** 2016-11-05 21:41 UTC
